version: '2'
services:
    wildfly:
        build: wildfly-appserver/.
        ports:
            - "8080:8080"
            - "9990:9990"
        links:
            - postgresdb:postgresql
        environment:
            - POSTGRES_PORT_5432_TCP_ADDR=postgresql
            - POSTGRES_PORT_5432_TCP_PORT=5432
            - POSTGRES_ENV_POSTGRES_USER=postgres
            - POSTGRES_ENV_POSTGRES_PASSWORD=admin
    postgresdb:
        build: postgres-database/.
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin


